print("hello github")
print("hello world")
print("python")
a = input("hello")
print(len(a))
print("another print")
name = input("Enter name: ")
print(f"{name=}")
age = int(input("Enter age: "))
print(f"{age*2=}")
print("another print")
